import React from 'react';

export default()=> {
  return (
    <div>
    <section className="section">
        <div className="container">
        <div className="content1">
        <h1 className="has-text-centered is-size-3 has-text-info has-text-weight-bold">Afforable Internet Marketing,Website design & SEO Services</h1>
        <p className="is-size-6">Web design encompasses many different skills and disciplines in the production and maintenance of
        <a href="#"><span className="has-text-link has-text-weight-bold">websites.</span></a>  The different areas of <a href="#"><span className="has-text-link has-text-weight-bold"> web design</span></a> include<a href="#"> <span className="has-text-link has-text-weight-bold">web graphic
        design; interface design;</span></a>  authoring, including standardised code and proprietary <a href="#"><span className="has-text-link has-text-weight-bold"> software; user experience design;</span></a> and search
        engine optimization. Often many individuals will work in teams covering different aspects of the design process, although some
        designers will cover them all.[1] The term <a href="#"><span className="has-text-link has-text-weight-bold"> "web design"</span></a> is normally used to describe the design process relating to the front-end
        (client side) design of a <a href="#"><span className="has-text-link has-text-weight-bold">website including writing markup.</span></a>  Web design partially overlaps web engineering in the broader scope of 
        <a href="#"><span className="has-text-link has-text-weight-bold">web development.</span></a> Web designers are expected to have an awareness of usability and if their role involves creating markup then they
        are also expected to be up to date with web accessibility guidelines.</p>
        </div>
        </div>
    </section>
    {/* End */}

    <section className="section">
        <div>
            <div className="columns">
                <div className="column">
               <div className="container">
                    <div className="content3">
                        <h2 className="is-size-3 has-text-weight-bold has-text-success">The SEO Compilicate Anylists Checklists</h2>
                    <p className="has-text-weight-bold">Web designers use a variety of different tools depending on what part of the production process they are involved in. 
                    These tools are updated over time by newer standards and software but the principles behind them remain the same. Web designers
                     use both vector and raster graphics editors to create web-formatted imagery or design prototypes.
                      Technologies used to create websites include W3C standards like<span className="has-text-info"> HTML and CSS,</span> which can be hand-coded or generated by WYSIWYG 
                      editing software. Other tools web designers might use include mark up validators[7] and other testing tools for usability and accessibility to ensure their websites meet web accessibility guidelines.[8]</p>
                    </div>
               </div>
                </div>
                <div className="column">
       <img src="https://5.imimg.com/data5/NH/FT/MY-4212527/responsive-web-designing-services-500x500.png"/>
                </div>

            </div>
        </div>
    </section>
    </div>
  );
}
